version: '3.8'

services:
  meteo-service:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 5006:5006
    networks:
      - meteo-network

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: meteo_history
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - meteo-network

networks:
  meteo-network:
