spring:
  application:
    name: openMeteo
  datasource:
    user: root
    password: example
    url: jdbc:postgresql://postgres:5432/meteo_history

server:
  port: 8080

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic