spring:
  application:
    name: openMeteo
  datasource:
    user: root
    password: example
    url: jdbc:postgresql://postgres:5432/meteo_history
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8080

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

open-meteo:
  name: open-meteo
  url: https://archive-api.open-meteo.com/v1/